apiVersion: v1
kind: Secret
metadata:
  name: rhlab-bot-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmFwcHMub2NwNC5yaC5sYWIiOiB7CiAgICAgICJhdXRoIjogImNtaHNZV0lyWW05ME9rczRSVGRVTjBrM1dscElURk5PT1ZkSU1qbFFVa2hWU1ZBeFNsbE9XVlJCVjBGVVdWRTBVemsxVkZGTU0wUkxUMVEwVmtFM1dUSkxTRlJYVWtsQ1JEQT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
