apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1-eth1-policy 
spec:
  nodeSelector: 
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
      - name: br1 
        description: Linux bridge with ens192 as a port 
        type: linux-bridge 
        state: up 
        ipv4:
          dhcp: true 
          enabled: true 
        bridge:
          options:
            stp:
              enabled: false 
          port:
            - name: ens192

