apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ens192
spec:
  desiredState:
    interfaces:
    - name: ens192
      type: ethernet
      state: up
      ipv4:
        dhcp: true
        enabled: true
