apiVersion: v1
data:
  config.yaml: |
    prometheusK8s:
      volumeClaimTemplate:
        metadata:
          name: prometheus-data
        spec:
          retention: 24h
          storageClassName: nfs-storage-provisioner
          resources:
            requests:
              storage: 10Gi
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
