apiVersion: batch/v1
kind: Job
metadata:
  name: stress-ng
spec:
  template:
    spec:
      containers:
      - name: stress-ng
        image: polinux/stress-ng
        resources:
          requests:
            memory: "256Mi"
            cpu: "1"
        #3   20  = 1
        #20  = 3 * 20 = 60
        command: ["/bin/bash", "-c", "for i in {1..60}; do stress-ng --cpu 3 --cpu-load 100 --timeout 10s;
sleep 10; done"]
      restartPolicy: Never
