apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
 name: local-file
 namespace: local-storage
spec:
 nodeSelector:
   nodeSelectorTerms:
   - matchExpressions:
       - key: cluster.ocs.openshift.io/openshift-storage
         operator: In
         values:
         - ""
 storageClassDevices:
   - storageClassName: localfile
     volumeMode: Filesystem
     devicePaths:
       - /dev/disk/by-id/scsi-36000c29dcd9d9f42deb3373dbac7495e
       - /dev/disk/by-id/scsi-36000c296605d5938eaab2c5035a0888f
       - /dev/disk/by-id/scsi-36000c292aff8a931eff0eac29e8e0062
