apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"config.openshift.io/v1","kind":"OAuth","metadata":{"annotations":{},"name":"cluster"},"spec":{"identityProviders":[{"htpasswd":{"fileData":{"name":"htpass-secret"}},"mappingMethod":"claim","name":"Local
      authentication","type":"HTPasswd"}]}}
    release.openshift.io/create-only: 'true'
  creationTimestamp: '2020-01-31T15:10:51Z'
  generation: 6
  name: cluster
  resourceVersion: '46370871'
  selfLink: /apis/config.openshift.io/v1/oauths/cluster
  uid: d11ec941-67f2-4b18-8366-283667472ae4
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: htpass-secret
      mappingMethod: claim
      name: Local authentication
      type: HTPasswd
    - ldap:
        attributes:
          email: []
          id:
            - dn
          name:
            - cn
          preferredUsername:
            - uid
        bindDN: 'cn=read-only-admin,dc=example,dc=com'
        bindPassword:
          name: ldap-bind-password-nzr58
        insecure: true
        url: 'ldap://ldap.forumsys.com/dc=example,dc=com'
      mappingMethod: claim
      name: LDAP
      type: LDAP

