apiVersion: v1
items:
- apiVersion: ocs.openshift.io/v1
  kind: StorageCluster
  metadata:
    generation: 3
    name: ocs-storagecluster
    namespace: openshift-storage
  spec:
    manageNodes: false
    resources:
      mds:
        requests:
          cpu: 1
          memory: 1Gi
      mgr:
        requests:
          cpu: 1
          memory: 1Gi
      osd:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 1Gi
      rgw:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 1Gi
    storageDeviceSets:
    - count: 1
      dataPVCTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: null
          volumeMode: Block
      name: ocs-deviceset
      placement: {}
      portable: true
      replica: 3
      resources: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
