apiVersion: v1
kind: Service
metadata:
  name: hello-keepalive
  annotations:
    keepalived-operator.redhat-cop.io/keepalivedgroup: keepalived-operator/keepalivedgroup-worker
spec:
  externalIPs:
    - 172.19.20.20
  type: ClusterIP    
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080 
  selector:
    app: hello-openshift
    deploymentconfig: hello-openshift
